---
apiVersion: v1
kind: Service
metadata:
  name: mock-provider
  labels:
    constraint.ciena.com/provider-latency: enabled
    constraint.ciena.com/provider-jitter: enabled
    constraint.ciena.com/provider-cpu-count: enabled
    constraint.ciena.com/provider-memory: enabled
    constraint.ciena.com/provider-space: enabled
spec:
  ports:
    - port: 5309
      protocol: TCP
      targetPort: 5309
  selector:
    app: mock-controller
  type: ClusterIP
