# permissions for end users to view constraintpolicybindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: constraintpolicybinding-viewer-role
rules:
- apiGroups:
  - constraint.ciena.com
  resources:
  - constraintpolicybindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - constraint.ciena.com
  resources:
  - constraintpolicybindings/status
  verbs:
  - get
