# permissions for end users to edit constraintpolicybindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: constraintpolicybinding-editor-role
rules:
- apiGroups:
  - constraint.ciena.com
  resources:
  - constraintpolicybindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - constraint.ciena.com
  resources:
  - constraintpolicybindings/status
  verbs:
  - get
