# permissions for end users to edit constraintpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: constraintpolicy-editor-role
rules:
- apiGroups:
  - constraint.ciena.com
  resources:
  - constraintpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - constraint.ciena.com
  resources:
  - constraintpolicies/status
  verbs:
  - get
