---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: turnbuckle-system
  name: constraint-policy-scheduler
  labels:
    app: constraint-policy-scheduler 
    component: constraint-policy-scheduler
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: constraint-policy-scheduler
subjects:
- kind: ServiceAccount
  name: constraint-policy-scheduler
  namespace: turnbuckle-system
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: system:kube-scheduler
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: constraint-policy-scheduler-pods
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: constraint-policy-scheduler-pods
subjects:
  - kind: ServiceAccount
    name: constraint-policy-scheduler
    namespace: turnbuckle-system
roleRef:
  kind: ClusterRole
  name: constraint-policy-scheduler-pods
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: constraint-policy-scheduler-nodes
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: constraint-policy-scheduler-nodes
subjects:
  - kind: ServiceAccount
    name: constraint-policy-scheduler
    namespace: turnbuckle-system
roleRef:
  kind: ClusterRole
  name: constraint-policy-scheduler-nodes
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: constraint-policy-scheduler-offers
rules:
  - apiGroups: ["constraint.ciena.com"]
    resources: ["constraintpolicyoffers"]
    verbs: ["create", "delete", "get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: constraint-policy-scheduler-offers
subjects:
  - kind: ServiceAccount
    name: constraint-policy-scheduler
    namespace: turnbuckle-system
roleRef:
  kind: ClusterRole
  name: constraint-policy-scheduler-offers
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: constraint-policy-scheduler-policies
rules:
  - apiGroups: ["constraint.ciena.com"]
    resources: ["constraintpolicies"]
    verbs: ["create", "delete", "get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: constraint-policy-scheduler-policies
subjects:
  - kind: ServiceAccount
    name: constraint-policy-scheduler
    namespace: turnbuckle-system
roleRef:
  kind: ClusterRole
  name: constraint-policy-scheduler-policies
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: constraint-policy-scheduler-endpoints
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: constraint-policy-scheduler-endpoints
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: constraint-policy-scheduler-endpoints
subjects:
- kind: ServiceAccount
  name: constraint-policy-scheduler
  namespace: turnbuckle-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: constraint-policy-scheduler-services
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: constraint-policy-scheduler-services
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: constraint-policy-scheduler-services
subjects:
- kind: ServiceAccount
  name: constraint-policy-scheduler
  namespace: turnbuckle-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: constraint-policy-scheduler-bindings
rules:
  - apiGroups: ["constraint.ciena.com"]
    resources: ["constraintpolicybindings"]
    verbs: ["create", "delete", "get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: constraint-policy-scheduler-bindings
subjects:
  - kind: ServiceAccount
    name: constraint-policy-scheduler
    namespace: turnbuckle-system
roleRef:
  kind: ClusterRole
  name: constraint-policy-scheduler-bindings
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: constraint-policy-scheduler
  namespace: turnbuckle-system
  labels:
    app: constraint-policy-scheduler
    app.kubernetes.io/name: constraint-policy-scheduler
    app.kubernetes.io/component: scheduler
    app.kubernetes.io/part-of: constraint-policy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: constraint-policy-scheduler
      app.kubernetes.io/name: constraint-policy-scheduler
      app.kubernetes.io/component: scheduler
      app.kubernetes.io/part-of: constraint-policy
  template:
    metadata:
      namespace: turnbuckle-system
      labels:
        app: constraint-policy-scheduler
        app.kubernetes.io/name: constraint-policy-scheduler
        app.kubernetes.io/component: scheduler
        app.kubernetes.io/part-of: constraint-policy
    spec:
      serviceAccount: constraint-policy-scheduler
      containers:
        - name: constraint-policy-scheduler
          image: IMAGE_SPEC
          imagePullPolicy: Always
          args:
            - "--debug=DEBUG_SPEC"
            - "--extender=EXTENDER_SPEC"
            - "--retry-on-no-offers=false"
            - "--num-retries-on-failure=5"
            - "--min-delay-on-failure=15s"
            - "--max-delay-on-failure=45s"
