---
apiVersion: v1
kind: Service
metadata:
  name: hello-server
spec:
  clusterIP: None
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: grpc
  selector:
    app: hello-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-server
  labels:
    app: hello-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-server
  template:
    metadata:
      labels:
        app: hello-server
    spec:
      schedulerName: connect-policy-scheduler
# Affinity not yet supported by connect-policy-scheduler
#      affinity:
#        podAntiAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#            - labelSelector:
#                matchExpressions:
#                  - key: app
#                    operator: In
#                    values:
#                      - hello-client
#              topologyKey: kubernetes.io/hostname
      containers:
        - name: server
          image: ciena/grpc-hello-server:0.1.0
          imagePullPolicy: Always
          args:
            - "--listen=:8080"
      terminationGracePeriodSeconds: 0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-client
  labels:
    app: hello-client
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-client
  template:
    metadata:
      labels:
        app: hello-client
    spec:
      schedulerName: connect-policy-scheduler
# Affinity not yet supported by connect-policy-scheduler
#      affinity:
#        podAntiAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#            - labelSelector:
#                matchExpressions:
#                  - key: app
#                    operator: In
#                    values:
#                      - hello-client
#              topologyKey: kubernetes.io/hostname
      containers:
        - name: client
          image: ciena/grpc-hello-client:0.1.0
          imagePullPolicy: Always
          args:
            - "--addr=hello-server.default.svc.cluster.local:8080"
            - "--interval=3s"
            - "--timeout=10s"
      terminationGracePeriodSeconds: 0
