apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base
images:
- name: mock
  newName: localhost:32000/rule-provider-mock
  newTag: v0.0.1-alpha
patches:
- ./patch-service.yaml
