apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base
images:
- name: mock
  newName: dockerhub.com/rule-provider-mock
  newTag: v0.0.1-alpha
patchesStrategicMerge:
- ./patch-service.yaml
