# Copyright 2022 Ciena Corporation.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
apiVersion: constraint.ciena.com/v1
kind: CostProvider
metadata:
  name: latencycost
  namespace: default
spec:
  priority: 10
  rule: latency
  target: ".*:.*:.*:Pod:hello.*"
  values:
   - node: ".*:.*control*"
     cost: 10
   - node: ".*:.*"
     cost: 3
---
apiVersion: constraint.ciena.com/v1
kind: CostProvider
metadata:
  name: memorycost
  namespace: default
spec:
  priority: 10
  rule: memory
  target: ".*:.*:.*:.*:hello.*"
  values:
   - node: ".*:.*control*"
     cost: 10
   - node: ".*:.*"
     cost: 3
---
apiVersion: constraint.ciena.com/v1
kind: CostProvider
metadata:
  name: cpucost
  namespace: default
spec:
  priority: 10
  rule: cpu-count
  target: ".*:.*:.*:.*:hello.*"
  values:
   - node: ".*:.*control*"
     cost: 1
   - node: ".*:.*"
     cost: 3
---
apiVersion: constraint.ciena.com/v1
kind: CostProvider
metadata:
  name: cpucost-server
  namespace: default
spec:
  priority: 11
  rule: cpu-count
  target: ".*:.*:.*:.*:hello-server.*"
  values:
   - node: ".*:.*control*"
     cost: 1
   - node: ".*:.*worker$"
     cost: 5
   - node: ".*:.*"
     cost: 1
---
apiVersion: constraint.ciena.com/v1
kind: CostProvider
metadata:
  name: jittercost
  namespace: default
spec:
  priority: 10
  rule: jitter
  target: ".*:.*:.*:.*:hello.*"
  values:
   - node: ".*:.*control*"
     cost: 10
   - node: ".*:.*"
     cost: 3
---
apiVersion: constraint.ciena.com/v1
kind: CostProvider
metadata:
  name: spacecost
  namespace: default
spec:
  priority: 10
  rule: space
  target: ".*:.*:.*:.*:hello.*"
  values:
   - node: ".*:.*control*"
     cost: 2
   - node: ".*:.*"
     cost: 3


