---
apiVersion: constraint.ciena.com/v1
kind: RuleProvider
metadata:
  name: test1
  namespace: default
spec:
  priority: 10
  rule: latency
  targets:
    - name: source
      reference: ".*:.*:.*:Pod:hello-client-.*"
    - name: destination
      reference: ".*:.*:.*:Pod:hello-server-.*"
  value: Limit
  reason: still working
---
apiVersion: constraint.ciena.com/v1
kind: RuleProvider
metadata:
  name: test2
  namespace: default
spec:
  priority: 10
  rule: memory
  targets:
    - name: default
      reference: ".*:.*:.*:.*:.*"
  value: Violation
  reason: Not good
