---
apiVersion: constraint.ciena.com/v1
kind: RuleProvider
metadata:
  name: test1
  namespace: default
spec:
  priority: 10
  rule: latency
  targets:
    - name: source
      reference: ".*:.*:.*:Pod:hello-client-.*"
    - name: destination
      reference: ".*:.*:.*:Pod:hello-server-.*"
  value: Compliant
  reason: OK
---
apiVersion: constraint.ciena.com/v1
kind: RuleProvider
metadata:
  name: test2
  namespace: default
spec:
  priority: 10
  rule: memory
  targets:
    - name: default
      reference: ".*:.*:.*:.*:.*"
  value: Compliant
  reason: OK
---
apiVersion: constraint.ciena.com/v1
kind: RuleProvider
metadata:
  name: test3
  namespace: default
spec:
  priority: 10
  rule: space
  targets:
    - name: default
      reference: ".*:.*:.*:.*:.*"
  value: Compliant
  reason: OK
---
apiVersion: constraint.ciena.com/v1
kind: RuleProvider
metadata:
  name: test4
  namespace: default
spec:
  priority: 10
  rule: cpu-count
  targets:
    - name: default
      reference: ".*:.*:.*:.*:.*"
  value: Compliant
  reason: OK
