name: Makefile CI Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Go environment
      uses: actions/setup-go@v2.1.5
      with:
        go-version: 1.17.6
      
    - name: Run build
      run: make build

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Go environment
      uses: actions/setup-go@v2.1.5
      with:
        go-version: 1.17.6
      
    - name: Run unit tests
      run: make test
