name: License Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  copyright:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Check License Header
      uses: apache/skywalking-eyes@v0.2.0
      with:
        log: info
        config: .licenserc.yaml
        token: ${{ github.token }}
        mode: check
